/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.Friend;
import backend.FriendManagement;
import backend.NewsFeed;
import backend.User;
import backend.UserSession;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author husse
 */
public class BlockedUsersPanel extends javax.swing.JPanel {

    private JList<String> blockedList;
    
    private DefaultListModel<String> blockedListModel;
    /**
     * Creates new form BlockedUsersPanel
     */
    public BlockedUsersPanel() {
        initComponents();
        blockedListModel = new DefaultListModel<>();
        // Set the JList models to DefaultListModel
        blockedList = new JList<>(blockedListModel);
        blockedList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) { 
                    String selectedBlock = blockedList.getSelectedValue();
                    String[] token = selectedBlock.split(" ");
                    String usernameUser = UserSession.getCurrentUser().getUsername();
                    Friend blocked = UserSession.getCurrentUser().getListOfBlockedFriends(token[0]);
                    String[] options = {"Unblock", "Ignore"};
                    int choice = JOptionPane.showOptionDialog(
                            null,
                            "Would you like to: ",
                            ("Blocked User: " + blocked.getUsername()),
                            JOptionPane.DEFAULT_OPTION,
                            JOptionPane.INFORMATION_MESSAGE,
                            null, options, options[0]
                    );
                    if (choice == 0) {
                        FriendManagement.blockFriend(UserSession.getCurrentUser(), blocked);
                        blockedListModel.removeElement(selectedBlock);
                        updateBlockedList(UserSession.getCurrentUser());
                    } else if (choice == 1) {
                    }
                }
            }
        }
        );
    }

    
    public void updateBlockedList(User u) {
        ArrayList<String> linerep = UserSession.getCurrentUser().getLineRepOfBlockedFriends();
        blockedListModel.clear();
        for (int i = 0; i < linerep.size(); i++) {
            blockedListModel.addElement(linerep.get(i));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
