/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.ImageHandler;
import backend.NewsFeed;
import backend.Posts;
import backend.Stories;
import backend.User;
import backend.UserSession;
import java.awt.Font;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author husse
 */
public class ContentPreviewForFriendsFrame extends javax.swing.JFrame {
    User user;
    /**
     * Creates new form ContentPreviewForFriendsFrame
     */

    public ContentPreviewForFriendsFrame(int selectedindix ,int type, User user) {
        initComponents();
        this.user = user;
        ContentLabel.setText(UserSession.getCurrentUser().getUsername()+ "'s recent updates");
        ContentLabel.setFont(new Font("Arial", Font.BOLD, 30));
        
        if(type == 1)
        {
            
                friendContentLabel.setIcon(ImageHandler.rescaleImageIcon(findPost(selectedindix).getImage(), 339, 339));
                 ContentLabel.setText(findPost(selectedindix).getContent());   
        }
        if(type == 2)
        {
            friendContentLabel.setIcon(ImageHandler.rescaleImageIcon(findStory(selectedindix).getImage(), 339, 339));
            ContentLabel.setText(findStory(selectedindix).getContent()); 
        }
        
       ContentLabel.setHorizontalTextPosition(JLabel.RIGHT);
        ContentLabel.setVerticalTextPosition(JLabel.CENTER);
        
        
        ContentLabel.setFont(new Font("Arial", Font.BOLD, 24));

        

    }
    

    public Posts findPost(int selectedindix) {
        
        Posts postChosen= NewsFeed.fetchPosts(UserSession.getCurrentUser()).get(selectedindix);
        return postChosen;
    }
    
    public Stories findStory(int selectedindix) {
       Stories storyChosen =  NewsFeed.fetchStories(UserSession.getCurrentUser()).get(selectedindix);
        return storyChosen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        friendContentLabel = new javax.swing.JLabel();
        ContentLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ContentLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(ContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(friendContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(friendContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(ContentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContentLabel;
    private javax.swing.JLabel friendContentLabel;
    // End of variables declaration//GEN-END:variables
}
