/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author husse
 */
public class ContentPreviewForUserFrame extends javax.swing.JFrame {
NewPostPanel2 newPostPanel;
    /**
     * Creates new form ImagePreviewFrame
     */
    public ContentPreviewForUserFrame(NewPostPanel2 newPostPanel, int contentType, ImageIcon imageIcon, String text) {
        initComponents();
        this.newPostPanel=newPostPanel;
        if(contentType==1){
        titleLabel.setText("Your post");
        }
        else if(contentType==2){
        titleLabel.setText("Your story");
        }
        titleLabel.setFont(new Font("Arial", Font.BOLD, 30));
        labelOfContent.setIcon(imageIcon);
        labelOfContent.setText(text);
        labelOfContent.setHorizontalTextPosition(JLabel.RIGHT);
        labelOfContent.setVerticalTextPosition(JLabel.CENTER);
        labelOfContent.setFont(new Font("Arial", Font.BOLD, 24));
    }

    

    // Optional: Add text below the image
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelOfContent = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        deleteContentButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setBackground(new java.awt.Color(102, 102, 255));
        titleLabel.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N

        deleteContentButton.setText("remove");
        deleteContentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteContentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelOfContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(deleteContentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteContentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelOfContent, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteContentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteContentButtonActionPerformed
        // TODO add your handling code here:
        try{
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you would like to delete the story?",
                "Remove Story",
                JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            newPostPanel.deleteContent(true);
        } else if (choice == JOptionPane.NO_OPTION) {
            System.out.println("User chose No");
        }}catch(Exception ex)
        {
            System.out.println("No choice was made");
            return;
       }
    }//GEN-LAST:event_deleteContentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteContentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelOfContent;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
