/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.FriendManagement;
import backend.NewsFeed;
import backend.User;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author malak
 */
public class FriendReqSuggPanel extends javax.swing.JPanel {

    private JList<String> friendsList;
    private JList<String> requestsList;
    private JList<String> suggestionsList;
    
    private DefaultListModel<String> friendsListModel;
    private DefaultListModel<String> requestsListModel;
    private DefaultListModel<String> suggestionsListModel;
    
    public FriendReqSuggPanel() {
        initComponents();
        friendsListModel = new DefaultListModel<>();
        requestsListModel = new DefaultListModel<>();
        suggestionsListModel = new DefaultListModel<>();
        // Set the JList models to DefaultListModel
        friendsList = new JList<>(friendsListModel);
        requestsList = new JList<>(requestsListModel);
        suggestionsList = new JList<>(suggestionsListModel);
        
         friendsList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) { 
                    String selectedStory = friendsList.getSelectedValue();

                    System.out.println("User selected: " + selectedStory);
                }
            }
        }
        );
         
         requestsList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) { 
                    String selectedStory = requestsList.getSelectedValue();

                    System.out.println("User selected: " + selectedStory);
                }
            }
        }
        );
         
          suggestionsList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) { 
                    String selectedStory = suggestionsList.getSelectedValue();

                    System.out.println("User selected: " + selectedStory);
                }
            }
        }
        );
    }

    public void updateFriendsList(User u) {
        ArrayList<String> linerep = NewsFeed.fetchFriends(u);
        friendsListModel.clear();

        for (int i = 0; i < linerep.size(); i++) {
            friendsListModel.addElement(linerep.get(i));
        }
    }
    
     public void updateSuggestionsList(User u) {
        ArrayList<String> linerep = FriendManagement.fetchFriendsSuggestions(u);
        suggestionsListModel.clear();

        for (int i = 0; i < linerep.size(); i++) {
            suggestionsListModel.addElement(linerep.get(i));
        }
    }
     
     public void updateRequestsList(User u) {
        ArrayList<String> linerep = u.getLineRepOfFriendReq();
        suggestionsListModel.clear();

        for (int i = 0; i < linerep.size(); i++) {
            suggestionsListModel.addElement(linerep.get(i));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
