/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.AccountManagement;
import backend.Group;
import backend.GroupManagement;
import backend.GroupSession;
import backend.GroupsDataBase;
import backend.User;
import backend.UserSession;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author pc castle
 */
public class groupMembersPanel extends javax.swing.JPanel {

    private DefaultListModel<String> groupMembersListModel = new DefaultListModel<>();
    private boolean memberslistUpdate = false;
    
    private DefaultListModel<String> groupAdminsListModel = new DefaultListModel<>();
    private boolean adminslistUpdate = false;
    
    private DefaultListModel<String> groupRequestsListModel = new DefaultListModel<>();
    private boolean requestlistUpdate = false;
    
    private boolean creator; 
    private boolean admin;
    
    
    
//    
//    private DefaultListModel<String> groupAdminsListModel = new DefaultListModel<>();
//    private boolean adminslistUpdate = false;
    /**
     * Creates new form groupMembersPanel
     */
    public groupMembersPanel() {
        initComponents();

        if(GroupSession.getCurrentGroup().getGroupCreator().equals(UserSession.getCurrentUser().getUserId()))
        {
            creator = true;
        }
        else 
        {
            creator = false;
        }
        if(GroupSession.getCurrentGroup().getGroupAdmins().contains(UserSession.getCurrentUser().getUserId()))
        {
            admin = true;
        }
        else 
        {
            admin = false;
        }
        
        
    }
    
    public boolean checkAdmin(String userId) {
        for (int i = 0; i < GroupSession.getCurrentGroup().getGroupAdmins().size(); i++) {
            if (userId.equals(GroupSession.getCurrentGroup().getGroupAdmins().get(i))) {
                return true;
            }
        }
        return false;
    }

    public boolean checkCreator(String userId) {
        if (userId.equals(GroupSession.getCurrentGroup().getGroupCreator())) {
            return true;
        }
        return false;
    }

    public void updateGroupMembersList(User u, Group g) {
        
        memberslistUpdate = true;
        ArrayList<String> linerep = GroupManagement.getLineRepresentationGroupMembers(GroupSession.getCurrentGroup());
        groupMembersListModel.clear();

        for (int i = 0; i < linerep.size(); i++) {
            groupMembersListModel.addElement(linerep.get(i));
        }
        System.out.println("Group Members List Data: " + linerep);
        groupRequestsList.setModel(groupMembersListModel);
        //this.user = u;
        memberslistUpdate = false;
    }
    
     public void updateGroupAdminsList(User u, Group g) {
        
        adminslistUpdate = true;
        ArrayList<String> linerep = GroupManagement.getLineRepresentationGroupAdmins(GroupSession.getCurrentGroup());
        groupAdminsListModel.clear();

        for (int i = 0; i < linerep.size(); i++) {
            groupAdminsListModel.addElement(linerep.get(i));
        }
        System.out.println("Group Members List Data: " + linerep);
        groupAdminsList.setModel(groupAdminsListModel);
        //this.user = u;
        adminslistUpdate = false;
    }

      public void updateGroupRequestsList(User u, Group g) {
        
        requestlistUpdate = true;
        ArrayList<String> linerep = GroupManagement.getLineRepresentationGroupRequests(GroupSession.getCurrentGroup());
        groupRequestsListModel.clear();

        for (int i = 0; i < linerep.size(); i++) {
            groupRequestsListModel.addElement(linerep.get(i));
        }
        System.out.println("Group Requests List Data: " + linerep);
        groupRequestsList.setModel(groupRequestsListModel);
        //this.user = u;
        requestlistUpdate = false;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        groupAdminsList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        groupMembersList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        groupRequestsList = new javax.swing.JList<>();

        groupAdminsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        groupAdminsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        groupAdminsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                groupAdminsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(groupAdminsList);

        jLabel1.setText("Group Admins");

        jLabel2.setText("Group Members");

        jLabel3.setText("Group Join Requests");

        groupMembersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        groupMembersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        groupMembersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                groupMembersListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(groupMembersList);

        groupRequestsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        groupRequestsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                groupRequestsListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(groupRequestsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(30, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(184, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(124, 124, 124)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(169, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(205, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void groupAdminsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_groupAdminsListValueChanged
        // TODO add your handling code here:
        if (!adminslistUpdate) {
            String selectedMember = groupAdminsList.getSelectedValue();

            if (selectedMember == null) {
                JOptionPane.showMessageDialog(this, "No admin selected");
                return;
            }

            if (creator) {
                String[] options = {"Remove From Group", "Demote To Member"};
                int choice = JOptionPane.showOptionDialog(
                        null,
                        "Would you like to: ",
                        ("Admin" + selectedMember),
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null, options, options[0]
                );
                
                String memberId= AccountManagement.findUserId(selectedMember);
                if (choice == 0) {
                    GroupSession.getCurrentGroup().removeUserFromGroupByCreator(memberId);
                    adminslistUpdate = true;
                    groupAdminsListModel.removeElement(selectedMember);
                    adminslistUpdate = false;
                    updateGroupAdminsList(UserSession.getCurrentUser(), GroupSession.getCurrentGroup());
                    updateGroupMembersList(UserSession.getCurrentUser(), GroupSession.getCurrentGroup());
                    JOptionPane.showMessageDialog(this, "Admin was removed successfully.");
                }
                if (choice == 1) {
                    GroupSession.getCurrentGroup().demoteAdminToMember(memberId);
                    adminslistUpdate = true;
                    groupAdminsListModel.removeElement(selectedMember);
                    adminslistUpdate = false;
                    updateGroupMembersList(UserSession.getCurrentUser(), GroupSession.getCurrentGroup());
                    updateGroupAdminsList(UserSession.getCurrentUser(), GroupSession.getCurrentGroup());
                    JOptionPane.showMessageDialog(this, "Your admin " + selectedMember + " is now a member in the group");
                }
                
            } else{
            JOptionPane.showMessageDialog(this, "Access denied. Only the creator can access Group Admins");
            }}
    }//GEN-LAST:event_groupAdminsListValueChanged

    private void groupMembersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_groupMembersListValueChanged
        // TODO add your handling code here:
        
    if (!memberslistUpdate) {
           String selectedMember = groupMembersList.getSelectedValue();

            if (selectedMember == null) {
                JOptionPane.showMessageDialog(this, "No member selected");
                return;
            }

            //boolean memberIsAdmin= checkAdmin(AccountManagement.findUserId(selectedMember));
            //boolean memberIsCreator= checkCreator(AccountManagement.findUserId(selectedMember));
            if (creator) {
                String[] options = {"Remove From Group", "Promote To Admin"};
                int choice = JOptionPane.showOptionDialog(
                        null,
                        "Would you like to: ",
                        ("Member" + selectedMember),
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null, options, options[0]
                );
                
                String memberId= AccountManagement.findUserId(selectedMember);
                if (choice == 0) {
                    GroupSession.getCurrentGroup().removeUserFromGroupByCreator(memberId);
                    memberslistUpdate = true;
                    groupMembersListModel.removeElement(selectedMember);
                    memberslistUpdate = false;
                    updateGroupMembersList(UserSession.getCurrentUser(), GroupSession.getCurrentGroup());
                    JOptionPane.showMessageDialog(this, "Member was removed successfully.");
                }
                if (choice == 1) {
                    GroupSession.getCurrentGroup().promoteMemberToAdmin(memberId);
                    memberslistUpdate = true;
                    groupMembersListModel.removeElement(selectedMember);
                    memberslistUpdate = false;
                    updateGroupMembersList(UserSession.getCurrentUser(), GroupSession.getCurrentGroup());
                    updateGroupAdminsList(UserSession.getCurrentUser(), GroupSession.getCurrentGroup());
                    JOptionPane.showMessageDialog(this, "Congratulations! You now have a new admin in your group:" + selectedMember);
                }
                
            } else if (admin) {
                String[] options = {"Remove From Group", "Ignore"};
                int choice = JOptionPane.showOptionDialog(
                        null,
                        "Would you like to: ",
                        ("Admin" + selectedMember),
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null, options, options[0]
                );
                String memberId= AccountManagement.findUserId(selectedMember);
                if (choice == 0) {
                    GroupSession.getCurrentGroup().removeUserFromGroupByAdmin(memberId);
                    memberslistUpdate = true;
                    groupMembersListModel.removeElement(selectedMember);
                    memberslistUpdate = false;
                    updateGroupMembersList(UserSession.getCurrentUser(), GroupSession.getCurrentGroup());
                    JOptionPane.showMessageDialog(this, "Member was removed successfully.");
                }
                if (choice == 1) {
                    System.out.println("Admin or Creator chose to ignore this member");
                    JOptionPane.showMessageDialog(this, "No action will be performed. \nA Creator can promote this user to become an admin");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Access denied. Only admins can access Group Members");
            }
        }
    }//GEN-LAST:event_groupMembersListValueChanged

    private void groupRequestsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_groupRequestsListValueChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_groupRequestsListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> groupAdminsList;
    private javax.swing.JList<String> groupMembersList;
    private javax.swing.JList<String> groupRequestsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
