/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.AccountManagement;
import backend.Group;
import backend.GroupManagement;
import backend.User;
import backend.UserSession;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author pc castle
 */
public class groupMembersPanel extends javax.swing.JPanel {
    User user;
    Group group;
    private DefaultListModel<String> groupMembersListModel = new DefaultListModel<>();
    private boolean memberslistUpdate = false;
    
    private DefaultListModel<String> groupAdminsListModel = new DefaultListModel<>();
    private boolean adminslistUpdate = false;
    boolean creator= checkCreator(user.getUserId()); 
    boolean admin = checkAdmin(user.getUserId()); 
//    
//    private DefaultListModel<String> groupAdminsListModel = new DefaultListModel<>();
//    private boolean adminslistUpdate = false;
    /**
     * Creates new form groupMembersPanel
     */
    public groupMembersPanel() {
        initComponents();
        this.user = UserSession.getCurrentUser();
        
        //must initialize here group with a static method that takes group chosen from newsfeed page group list
    }
    
    public boolean checkAdmin(String userId) {
        for (int i = 0; i < group.getGroupAdmins().size(); i++) {
            if (userId.equals(group.getGroupAdmins().get(i))) {
                return true;
            }
        }
        return false;
    }

    public boolean checkCreator(String userId) {
        if (userId.equals(group.getGroupCreator())) {
            return true;
        }
        return false;
    }

    public void updateGroupMembersList(User u, Group g) {
        
        memberslistUpdate = true;
        ArrayList<String> linerep = GroupManagement.getLineRepresentationGroupMembers(group);
        groupMembersListModel.clear();

        for (int i = 0; i < linerep.size(); i++) {
            groupMembersListModel.addElement(linerep.get(i));
        }
        System.out.println("Group Members List Data: " + linerep);
        groupMembersList.setModel(groupMembersListModel);
        //this.user = u;
        memberslistUpdate = false;
    }
    
     public void updateGroupAdminsList(User u, Group g) {
        
        adminslistUpdate = true;
        ArrayList<String> linerep = GroupManagement.getLineRepresentationGroupAdmins(group);
        groupAdminsListModel.clear();

        for (int i = 0; i < linerep.size(); i++) {
            groupAdminsListModel.addElement(linerep.get(i));
        }
        System.out.println("Group Members List Data: " + linerep);
        groupAdminsList.setModel(groupAdminsListModel);
        //this.user = u;
        adminslistUpdate = false;
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        groupMembersList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        groupAdminsList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        groupRequestsList = new javax.swing.JList<>();

        groupMembersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        groupMembersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        groupMembersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                groupMembersListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(groupMembersList);

        groupAdminsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        groupAdminsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        groupAdminsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                groupAdminsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(groupAdminsList);

        groupRequestsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        groupRequestsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        groupRequestsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                groupRequestsListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(groupRequestsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void groupMembersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_groupMembersListValueChanged
        // TODO add your handling code here:
        if (!memberslistUpdate) {
            String selectedMember = groupMembersList.getSelectedValue();

            if (selectedMember == null) {
                JOptionPane.showMessageDialog(this, "No member selected");
                return;
            }

            //boolean memberIsAdmin= checkAdmin(AccountManagement.findUserId(selectedMember));
            //boolean memberIsCreator= checkCreator(AccountManagement.findUserId(selectedMember));
            if (creator) {
                String[] options = {"Remove From Group", "Promote To Admin"};
                int choice = JOptionPane.showOptionDialog(
                        null,
                        "Would you like to: ",
                        ("Admin" + AccountManagement.findUsername(selectedMember)),
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null, options, options[0]
                );
                if (choice == 0) {
                    

                }
                if (choice == 1) {

                }
            } else if (admin) {
                String[] options = {"Remove From Group", "Ignore"};
                int choice = JOptionPane.showOptionDialog(
                        null,
                        "Would you like to: ",
                        ("Admin" + AccountManagement.findUsername(selectedMember)),
                        JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null, options, options[0]
                );
                if (choice == 0) {

                }
                if (choice == 1) {

                }
            } else {
                JOptionPane.showMessageDialog(this, "Access denied. Only admins can access Group Members");
            }
        }
    
    }//GEN-LAST:event_groupMembersListValueChanged

    private void groupAdminsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_groupAdminsListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_groupAdminsListValueChanged

    private void groupRequestsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_groupRequestsListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_groupRequestsListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> groupAdminsList;
    private javax.swing.JList<String> groupMembersList;
    private javax.swing.JList<String> groupRequestsList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
