/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.Group;
import backend.User;

/**
 *
 * @author pc castle
 */
public class GroupManagementPage extends javax.swing.JFrame {
 private static GroupManagementPage instance;
    private Group group;
    private User user;
    /**
     * Creates new form GroupManagement
     */
    
    
    
    private GroupManagementPage(Group group) {
        initComponents();
        this.group= group;
        
        
        //groupMembersPanel1.updateGroupMembersList(user, group);
        //groupMembersPanel1.updateGroupAdminsList(user);
        //groupMembersPanel1.updateGroupRequestsList(user);
    }

     public static GroupManagementPage getInstance(Group group) {
        if (instance == null) {
            instance = new GroupManagementPage(group);
        }
        return instance;
    }
     
    public void openNewsFeedPage(User u) {
        this.setVisible(false);
        NewsFeedPage nfp = NewsFeedPage.getInstance(u);
        nfp.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeButton = new javax.swing.JButton();
        groupPhotoLabel = new javax.swing.JLabel();
        groupNameLabel = new javax.swing.JLabel();
        groupDescriptionLabel = new javax.swing.JLabel();
        userPositionLabel = new javax.swing.JLabel();
        groupPostsLabel = new javax.swing.JLabel();
        groupMembersLabel = new javax.swing.JLabel();
        groupPostsPanel1 = new frontend.groupPostsPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homeButton.setText("Go Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton);

        groupPhotoLabel.setText("group photo");
        getContentPane().add(groupPhotoLabel);

        groupNameLabel.setText("group name");
        getContentPane().add(groupNameLabel);

        groupDescriptionLabel.setText("group description");
        getContentPane().add(groupDescriptionLabel);

        userPositionLabel.setText("your position");
        getContentPane().add(userPositionLabel);

        groupPostsLabel.setText("Recent Posts");
        getContentPane().add(groupPostsLabel);

        groupMembersLabel.setText("Group Members");
        getContentPane().add(groupMembersLabel);
        getContentPane().add(groupPostsPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.openNewsFeedPage(user);
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GroupManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GroupManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GroupManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GroupManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GroupManagementPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel groupDescriptionLabel;
    private javax.swing.JLabel groupMembersLabel;
    private javax.swing.JLabel groupNameLabel;
    private javax.swing.JLabel groupPhotoLabel;
    private javax.swing.JLabel groupPostsLabel;
    private frontend.groupPostsPanel groupPostsPanel1;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel userPositionLabel;
    // End of variables declaration//GEN-END:variables
}
