/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.Group;
import backend.GroupSession;
import backend.GroupsDataBase;
import backend.User;
import javax.swing.JOptionPane;

/**
 *
 * @author pc castle
 */

public class GroupCreationFrame extends javax.swing.JFrame {

    private static int groupID = 0;
    private static GroupCreationFrame instance;
    /**
     * Creates new form GroupCreationFrame
     */
    public GroupCreationFrame() {
        initComponents();
    }
    
    public static GroupCreationFrame getInstance() {
        if (instance == null) {
            instance = new GroupCreationFrame();
        }
        return instance;
    }
    
    public void openGroupPreviewFrame(Group group) {
        this.setVisible(false);
        GroupManagementPage gpf = GroupManagementPage.getInstance(group);
        gpf.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        groupNameLabel = new javax.swing.JLabel();
        groupNameLabel1 = new javax.swing.JLabel();
        groupNameTextField = new javax.swing.JTextField();
        groupDescriptionTextField = new javax.swing.JTextField();
        createGroupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Your Own Group Now!");

        groupNameLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        groupNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        groupNameLabel.setText("Group Name:");

        groupNameLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        groupNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        groupNameLabel1.setText("Group Description");

        groupNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupNameTextFieldActionPerformed(evt);
            }
        });

        groupDescriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupDescriptionTextFieldActionPerformed(evt);
            }
        });

        createGroupButton.setBackground(new java.awt.Color(102, 153, 255));
        createGroupButton.setText("CREATE GROUP");
        createGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(groupNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(groupNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(groupDescriptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(groupNameTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(createGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupNameTextFieldActionPerformed

    private void groupDescriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupDescriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupDescriptionTextFieldActionPerformed

    private void createGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupButtonActionPerformed
        // TODO add your handling code here:
        String groupName = groupNameTextField.getText();
        int flagfail=0; 
        for (int i = 0; i < GroupsDataBase.getInstance().getAllGlobalGroups().size(); i++) {
            if (GroupsDataBase.getInstance().getAllGlobalGroups().get(i).getGroupName().equals(groupName)) {
                JOptionPane.showMessageDialog(this, "The group name entered already exists. Please choose another one");
                flagfail=1;
                break;
            }
        }
        String groupDescription = groupDescriptionTextField.getText();
        String creatorId = backend.UserSession.getCurrentUser().getUserId();

        if(flagfail==0){
        Group group = new Group("G" + groupID, groupName, groupDescription, creatorId, null);
        group.addGroupAdmin(backend.UserSession.getCurrentUser().getUserId());
        group.addGroupMember(backend.UserSession.getCurrentUser().getUserId());
        group.setGroupCreator(backend.UserSession.getCurrentUser().getUserId());
        
        GroupsDataBase.getInstance().addToGlobalGroups(group);
        
        backend.UserSession.getCurrentUser().addToGroups(group);
        
        GroupSession.setCurrentGroup(group);
        this.openGroupPreviewFrame(GroupSession.getCurrentGroup());

        }
    }//GEN-LAST:event_createGroupButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        NewsFeedPage.getInstance(backend.UserSession.getCurrentUser()).setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createGroupButton;
    private javax.swing.JTextField groupDescriptionTextField;
    private javax.swing.JLabel groupNameLabel;
    private javax.swing.JLabel groupNameLabel1;
    private javax.swing.JTextField groupNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
