/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author malak
 */
public class GroupsListFrame extends javax.swing.JFrame {

    /**
     * Creates new form GroupsListFrame
     */
    boolean groupsListUpdate = false;
    DefaultListModel<String> groupsListModel = new DefaultListModel();
    private static GroupsListFrame instance = null;
    private GroupsListFrame() {
        initComponents();
        
    }
    
    public static GroupsListFrame getInstance()
    {
        if(instance == null)
        {
            instance = new GroupsListFrame();
        }
        return instance;
    }
    

    public void updateNotificationsList() {

        groupsListUpdate = true;
        ArrayList<String> linerep = backend.UserSession.getCurrentUser().getLineRepresentationForUserGroups();
        groupsListModel.clear();

        for (int i = 0; i < linerep.size(); i++) {
            groupsListModel.addElement(linerep.get(i));
        }
        GroupsList.setModel(groupsListModel);
        groupsListUpdate = false;
        System.out.println("Notifications List Data: " + linerep);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GroupsList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your Groups");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 16, 234, 28));

        GroupsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(GroupsList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 56, 347, 195));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/purple-gradient-background-5472-x-3648-i2xtxsy5ijm2ik4e.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> GroupsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
