/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.NewsFeed;
import backend.Stories;

/**
 *
 * @author malak
 */
public class StoriesIcon extends javax.swing.JPanel {

    /**
     * Creates new form StoriesIcon
     */
    private String id;
    public StoriesIcon() {
        initComponents();
    }

    public StoriesIcon(String id) {
        initComponents();
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/result_DefaultPhoto.jpg"))); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 5, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        Stories story = NewsFeed.findStoryUsingContentId(id);
        ContentPreviewForFriendsFrame frame = new ContentPreviewForFriendsFrame(story);
        frame.setVisible(true);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
