/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.ImageHandler;
import backend.NewsFeed;
import backend.Profile;
import backend.User;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author husse
 */
public class UserContentPanel extends javax.swing.JPanel {

    private static UserContentPanel instance;

    private DefaultListModel<String> postsListModel= new DefaultListModel<>();
    private DefaultListModel<String> storiesListModel = new DefaultListModel<>();

    boolean storiesListUpdate = false;
    boolean postsListUpdate = false;
    User user;
   
    /**
     * Creates new form UserContentPanel
     */
    public UserContentPanel() {
        initComponents();
                postsList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) { 
                   if(!postsListUpdate){ 
                    int selectedindix = postsList.getSelectedIndex();
                    ContentPreviewForSavedUserContentFrame usercontent= new ContentPreviewForSavedUserContentFrame(selectedindix,1);
                    usercontent.setVisible(true);
                }}
            }
        }
        );

        storiesList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {

                   if(!storiesListUpdate){
                    int selectedindix = storiesList.getSelectedIndex();
                    ContentPreviewForSavedUserContentFrame usercontent= new ContentPreviewForSavedUserContentFrame(selectedindix, 2);
                    usercontent.setVisible(true);
                    
                   }
            }
        }}
        );
    }

    public void updateStoriesList(User u) {
        storiesListUpdate = true;
        this.user = u;
        System.out.println("updateStoriesList called with user: " + u);
        ArrayList<String> linerep = NewsFeed.getLineRepresentationsStories(u);
        storiesListModel.clear();

        for (int i = 0; i < linerep.size(); i++) {
            storiesListModel.addElement(linerep.get(i));
            System.out.println("Fetched stories: " + linerep);
        }
        storiesList.setModel(storiesListModel);
        storiesListUpdate = false;
        System.out.println("Stories: " + linerep);
    }

    public void updatePostsList(User u) {
        this.user = u;
        System.out.println("updatePostsList called with user: " + u);
        postsListUpdate = true;
        ArrayList<String> linerep = NewsFeed.getLineRepresentationsPosts(u);
        postsListModel.clear();

        for (int i = 0; i < linerep.size(); i++) {
            postsListModel.addElement(linerep.get(i));
            System.out.println("Fetched posts: " + linerep);

        }
        postsList.setModel(postsListModel);
        postsListUpdate = false;
    }

   
    public static UserContentPanel getInstance() {
        if (instance == null) {
            instance = new UserContentPanel();
        }
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        storiesList = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        postsList = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        storiesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(storiesList);

        postsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(postsList);

        jLabel7.setText("Your posts");

        jLabel6.setText("Your stories");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                        .addComponent(jScrollPane5)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> postsList;
    private javax.swing.JList<String> storiesList;
    // End of variables declaration//GEN-END:variables
}
